### ISSUE TITLE
Alternative syntax for autofocus

### ISSUE THREAD

**Issue by brendon** [amiel/html5support#2]
Hi there, thanks for this great plugin :)

You might want to add support for the following syntax of autofocus as I use simple_form in Rails to generate the forms and it spits out autofocus="autofocus" which is still valid html I think:

```
$('[autofocus="autofocus"]').autofocus();
```

I've just hacked around this in my app but it'd probably make a good addition to the code. Sorry for not supplying a patch but I thought this would probably be simpler for you to quickly change :)

**Comment by amiel** [comment]
Hi @brendon, thanks for the note.

Did you try your code with this plugin? I'm almost certain that

``` javascript
$('[autofocus="autofocus"]').autofocus();
```

will already work.

Also, did you try using

``` javascript
$.autofocus();
```

with simple_form, I'm also almost positive that it should work without any changes.

Please let me know if either of those don't work.

**Comment by brendon** [comment]
Hi Amiel, your javascript by itself didn't work, but

```
$('[autofocus="autofocus"]').autofocus();
```

did work. I only thought to try that after it wasn't working and so I had a
look through your code where I saw the shortened selector. This is in IE9
on Windows 7. Naturally I would think that the shorthand selector would
still work because the attribute exists whether it has a value or not.
Though it's interesting to note that JQuery 1.6 and greater make a
distinction between attributes and properties (where autofocus would
probably be a property) so perhaps it's refusing to select it?

I guess the ideal situation would be where both selectors are catered for :)

Have a great day! :D

Brendon

On Fri, Feb 17, 2012 at 1:20 PM, Amiel Martin <
reply@reply.github.com

**Comment by amiel** [comment]
@brendon just to double check, when you say the javascript by itself didn't work, did you call

``` javascript
$.autofocus();
```

in a jquery ready block?

I'd love to fix this issue for you, but I can't reproduce it. What browser?
Could you provide a full example of the undesired behavior?

**Comment by brendon** [comment]
Hi Amiel, thanks for getting back to me. In my testing it wasn't working on
IE9 on Windows 7. I'll have a play around and see if I can get more solid
data for you :)

Cheers,

Brendon

On Thu, Mar 1, 2012 at 8:30 AM, Amiel Martin <
reply@reply.github.com

**Comment by brendon** [comment]
Hi Amiel, it might be related to this:

http://bugs.jquery.com/ticket/5637

I'm using query 1.6 but will update now. Looks like they've fixed it in
later versions :)

Cheers,

Brendon

**Comment by amiel** [comment]
Sweet, thanks for looking into this.

I'll mark the issue as closed. Feel free to re-open if it doesn't work for you with jquery 1.7.

**Comment by brendon** [comment]
Thanks Amiel :D

On Fri, Mar 9, 2012 at 2:06 PM, Amiel Martin <
reply@reply.github.com
