### ISSUE TITLE
focus event should always clear placeholder class

### ISSUE THREAD

**Issue by davidcl64** [amiel/html5support#7]
Currently the placeholder class is only cleared when an input element gains focus AND its value is the placeholder text.

This is an issue if the value of the field is already set before being bound by placeholder.

The logic should look like this:

```
clear_value = function() {
        if (self.val() == value) {
            self.val('');
        }
        self.removeClass(placeholder_klass);
 };
```

**Comment by amiel** [comment]
@davidcl64 Thanks for pointing this out.

I took a minute to try and recreate the situation that you are talking about, and then realized that I don't have any browsers that don't support placeholder.

Do you want to submit a pull-request?

**Comment by davidcl64** [comment]
Done!  Thanks for taking a look and thanks for writing this in the first place..  Saved me some time :)
