### ISSUE TITLE
Non-printable characters are already encoded in minified version -- leads to []'s in some browsers

### ISSUE THREAD

**Issue by mjvotaw** [amiel/html5support#9]
In IE 8, I noticed that the unprintable \u00A0 characters were showing up as [] glyphs (whatever those are called). After switching to the un-minified version of the plugin, the issue went away. I realized then it was because the characters were already encoded in the minified version. 
You can see what I mean here:
![screen shot 2013-09-25 at 5 31 28 pm](https://f.cloud.github.com/assets/1308043/1213863/83d1ddda-2632-11e3-9a42-43f68e46b87c.png)

The solution is very simple: just replace the encoded characters with the actual Unicode escape sequence.

**Comment by amiel** [comment]
I'll happily merge a pull-request if you have a moment to put in the unicode escape sequence. Otherwise Il'l take a look during my next open-source time.

Thanks for the issue!

**Comment by goofballLogic** [comment]
But note that you may need to update your minification tool's configuration so this change doesn't disappear again...
